{
	"MsgInfos" : [
		{
			"MsgType" : 101,
			"MsgName" : "S2WServerStart"
		},
		{
			"MsgType" : 102,
			"MsgName" : "W2SServerStartRes"
		},
		{
			"MsgType" : 103,
			"MsgName" : "S2WSendInfo"
		},
		{
			"MsgType" : 104,
			"MsgName" : "W2SSendInfo"
		},
		{
			"MsgType" : 105,
			"MsgName" : "W2SDispatch"
		},
		{
			"MsgType" : 106,
			"MsgName" : "W2SBroadcast"
		},
		{
			"MsgType" : 107,
			"MsgName" : "S2WRoleInfoChange"
		},
		{
			"MsgType" : 108,
			"MsgName" : "S2WRoleInfoRequest"
		},
		{
			"MsgType" : 109,
			"MsgName" : "W2SRoleInfoResponse"
		}
	]
}
