// Code generated by protoc-gen-go.
// source: world.proto
// DO NOT EDIT!

/*
Package msgProto is a generated protocol buffer package.

It is generated from these files:
	world.proto

It has these top-level messages:
	S2WServerStart
	W2SServerStartRes
	S2WSendInfo
	W2SSendInfo
	W2SDispatch
	W2SBroadcast
	S2WRoleInfoChange
	S2WRoleInfoRequest
	W2SRoleInfoResponse
*/
package msgProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type S2WRoleInfoRequest_ReqType int32

const (
	S2WRoleInfoRequest_ROLE_LIST  S2WRoleInfoRequest_ReqType = 0
	S2WRoleInfoRequest_LAST_LOGIN S2WRoleInfoRequest_ReqType = 1
)

var S2WRoleInfoRequest_ReqType_name = map[int32]string{
	0: "ROLE_LIST",
	1: "LAST_LOGIN",
}
var S2WRoleInfoRequest_ReqType_value = map[string]int32{
	"ROLE_LIST":  0,
	"LAST_LOGIN": 1,
}

func (x S2WRoleInfoRequest_ReqType) String() string {
	return proto.EnumName(S2WRoleInfoRequest_ReqType_name, int32(x))
}
func (S2WRoleInfoRequest_ReqType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

type S2WServerStart struct {
	ZoneId uint32 `protobuf:"varint,1,opt,name=zoneId" json:"zoneId,omitempty"`
}

func (m *S2WServerStart) Reset()                    { *m = S2WServerStart{} }
func (m *S2WServerStart) String() string            { return proto.CompactTextString(m) }
func (*S2WServerStart) ProtoMessage()               {}
func (*S2WServerStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *S2WServerStart) GetZoneId() uint32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

type W2SServerStartRes struct {
}

func (m *W2SServerStartRes) Reset()                    { *m = W2SServerStartRes{} }
func (m *W2SServerStartRes) String() string            { return proto.CompactTextString(m) }
func (*W2SServerStartRes) ProtoMessage()               {}
func (*W2SServerStartRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type S2WSendInfo struct {
	ZoneId uint32 `protobuf:"varint,1,opt,name=zoneId" json:"zoneId,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	Type   uint32 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Info   string `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
}

func (m *S2WSendInfo) Reset()                    { *m = S2WSendInfo{} }
func (m *S2WSendInfo) String() string            { return proto.CompactTextString(m) }
func (*S2WSendInfo) ProtoMessage()               {}
func (*S2WSendInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *S2WSendInfo) GetZoneId() uint32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *S2WSendInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *S2WSendInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *S2WSendInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type W2SSendInfo struct {
	ZoneId uint32 `protobuf:"varint,1,opt,name=zoneId" json:"zoneId,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	Type   uint32 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Info   string `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
}

func (m *W2SSendInfo) Reset()                    { *m = W2SSendInfo{} }
func (m *W2SSendInfo) String() string            { return proto.CompactTextString(m) }
func (*W2SSendInfo) ProtoMessage()               {}
func (*W2SSendInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *W2SSendInfo) GetZoneId() uint32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *W2SSendInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *W2SSendInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *W2SSendInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type W2SDispatch struct {
	FromZoneId uint32 `protobuf:"varint,1,opt,name=fromZoneId" json:"fromZoneId,omitempty"`
	ToZoneId   uint32 `protobuf:"varint,2,opt,name=toZoneId" json:"toZoneId,omitempty"`
	Type       uint32 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Info       string `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
}

func (m *W2SDispatch) Reset()                    { *m = W2SDispatch{} }
func (m *W2SDispatch) String() string            { return proto.CompactTextString(m) }
func (*W2SDispatch) ProtoMessage()               {}
func (*W2SDispatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *W2SDispatch) GetFromZoneId() uint32 {
	if m != nil {
		return m.FromZoneId
	}
	return 0
}

func (m *W2SDispatch) GetToZoneId() uint32 {
	if m != nil {
		return m.ToZoneId
	}
	return 0
}

func (m *W2SDispatch) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *W2SDispatch) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type W2SBroadcast struct {
	ZoneIds []uint32 `protobuf:"varint,1,rep,packed,name=zoneIds" json:"zoneIds,omitempty"`
	Type    uint32   `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Info    string   `protobuf:"bytes,3,opt,name=info" json:"info,omitempty"`
}

func (m *W2SBroadcast) Reset()                    { *m = W2SBroadcast{} }
func (m *W2SBroadcast) String() string            { return proto.CompactTextString(m) }
func (*W2SBroadcast) ProtoMessage()               {}
func (*W2SBroadcast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *W2SBroadcast) GetZoneIds() []uint32 {
	if m != nil {
		return m.ZoneIds
	}
	return nil
}

func (m *W2SBroadcast) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *W2SBroadcast) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type S2WRoleInfoChange struct {
	ZoneId uint32                      `protobuf:"varint,1,opt,name=zoneId" json:"zoneId,omitempty"`
	UserId string                      `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	RoleId uint64                      `protobuf:"varint,3,opt,name=roleId" json:"roleId,omitempty"`
	Info   *S2WRoleInfoChange_RoleInfo `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
}

func (m *S2WRoleInfoChange) Reset()                    { *m = S2WRoleInfoChange{} }
func (m *S2WRoleInfoChange) String() string            { return proto.CompactTextString(m) }
func (*S2WRoleInfoChange) ProtoMessage()               {}
func (*S2WRoleInfoChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *S2WRoleInfoChange) GetZoneId() uint32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *S2WRoleInfoChange) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *S2WRoleInfoChange) GetRoleId() uint64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *S2WRoleInfoChange) GetInfo() *S2WRoleInfoChange_RoleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type S2WRoleInfoChange_RoleInfo struct {
	RoleId   uint64 `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=roleName" json:"roleName,omitempty"`
	Level    uint32 `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	School   uint32 `protobuf:"varint,4,opt,name=school" json:"school,omitempty"`
	Sex      uint32 `protobuf:"varint,5,opt,name=sex" json:"sex,omitempty"`
	Lasttime uint64 `protobuf:"varint,6,opt,name=lasttime" json:"lasttime,omitempty"`
}

func (m *S2WRoleInfoChange_RoleInfo) Reset()                    { *m = S2WRoleInfoChange_RoleInfo{} }
func (m *S2WRoleInfoChange_RoleInfo) String() string            { return proto.CompactTextString(m) }
func (*S2WRoleInfoChange_RoleInfo) ProtoMessage()               {}
func (*S2WRoleInfoChange_RoleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *S2WRoleInfoChange_RoleInfo) GetRoleId() uint64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *S2WRoleInfoChange_RoleInfo) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *S2WRoleInfoChange_RoleInfo) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *S2WRoleInfoChange_RoleInfo) GetSchool() uint32 {
	if m != nil {
		return m.School
	}
	return 0
}

func (m *S2WRoleInfoChange_RoleInfo) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *S2WRoleInfoChange_RoleInfo) GetLasttime() uint64 {
	if m != nil {
		return m.Lasttime
	}
	return 0
}

type S2WRoleInfoRequest struct {
	ZoneId uint32                     `protobuf:"varint,1,opt,name=zoneId" json:"zoneId,omitempty"`
	UserId string                     `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	RoleId uint64                     `protobuf:"varint,3,opt,name=roleId" json:"roleId,omitempty"`
	Req    S2WRoleInfoRequest_ReqType `protobuf:"varint,4,opt,name=req,enum=msgProto.S2WRoleInfoRequest_ReqType" json:"req,omitempty"`
}

func (m *S2WRoleInfoRequest) Reset()                    { *m = S2WRoleInfoRequest{} }
func (m *S2WRoleInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*S2WRoleInfoRequest) ProtoMessage()               {}
func (*S2WRoleInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *S2WRoleInfoRequest) GetZoneId() uint32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *S2WRoleInfoRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *S2WRoleInfoRequest) GetRoleId() uint64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *S2WRoleInfoRequest) GetReq() S2WRoleInfoRequest_ReqType {
	if m != nil {
		return m.Req
	}
	return S2WRoleInfoRequest_ROLE_LIST
}

type W2SRoleInfoResponse struct {
	RoleId uint64                        `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	Req    S2WRoleInfoRequest_ReqType    `protobuf:"varint,2,opt,name=req,enum=msgProto.S2WRoleInfoRequest_ReqType" json:"req,omitempty"`
	Info   []*S2WRoleInfoChange_RoleInfo `protobuf:"bytes,3,rep,name=info" json:"info,omitempty"`
}

func (m *W2SRoleInfoResponse) Reset()                    { *m = W2SRoleInfoResponse{} }
func (m *W2SRoleInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*W2SRoleInfoResponse) ProtoMessage()               {}
func (*W2SRoleInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *W2SRoleInfoResponse) GetRoleId() uint64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *W2SRoleInfoResponse) GetReq() S2WRoleInfoRequest_ReqType {
	if m != nil {
		return m.Req
	}
	return S2WRoleInfoRequest_ROLE_LIST
}

func (m *W2SRoleInfoResponse) GetInfo() []*S2WRoleInfoChange_RoleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*S2WServerStart)(nil), "msgProto.S2WServerStart")
	proto.RegisterType((*W2SServerStartRes)(nil), "msgProto.W2SServerStartRes")
	proto.RegisterType((*S2WSendInfo)(nil), "msgProto.S2WSendInfo")
	proto.RegisterType((*W2SSendInfo)(nil), "msgProto.W2SSendInfo")
	proto.RegisterType((*W2SDispatch)(nil), "msgProto.W2SDispatch")
	proto.RegisterType((*W2SBroadcast)(nil), "msgProto.W2SBroadcast")
	proto.RegisterType((*S2WRoleInfoChange)(nil), "msgProto.S2WRoleInfoChange")
	proto.RegisterType((*S2WRoleInfoChange_RoleInfo)(nil), "msgProto.S2WRoleInfoChange.RoleInfo")
	proto.RegisterType((*S2WRoleInfoRequest)(nil), "msgProto.S2WRoleInfoRequest")
	proto.RegisterType((*W2SRoleInfoResponse)(nil), "msgProto.W2SRoleInfoResponse")
	proto.RegisterEnum("msgProto.S2WRoleInfoRequest_ReqType", S2WRoleInfoRequest_ReqType_name, S2WRoleInfoRequest_ReqType_value)
}

func init() { proto.RegisterFile("world.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0x9d, 0xec, 0x34, 0x4d, 0x6f, 0x96, 0x90, 0xaa, 0xa3, 0x98, 0x3c, 0x8c, 0x60, 0xf6, 0xe0,
	0x27, 0x3f, 0x78, 0x30, 0xf6, 0xba, 0x2f, 0x86, 0x21, 0xb4, 0x45, 0x0a, 0x18, 0xf6, 0x52, 0xbc,
	0xf8, 0xa6, 0x09, 0x38, 0x96, 0x23, 0xa9, 0xdd, 0xba, 0x9f, 0xb2, 0x97, 0xfd, 0x87, 0xfd, 0x80,
	0xfd, 0xb6, 0x21, 0x45, 0xf1, 0x3c, 0xb6, 0xc0, 0x02, 0xeb, 0xdb, 0x3d, 0x57, 0xba, 0xe7, 0x9c,
	0x7b, 0x64, 0x0c, 0xfd, 0x4f, 0x42, 0x96, 0x45, 0x5c, 0x4b, 0xa1, 0x05, 0xed, 0xad, 0xd5, 0xcd,
	0x95, 0xa9, 0xc2, 0x08, 0x86, 0x3c, 0xc9, 0x38, 0xca, 0x3b, 0x94, 0x5c, 0xe7, 0x52, 0xd3, 0x73,
	0xe8, 0x7e, 0x11, 0x15, 0xa6, 0x45, 0x40, 0x26, 0x24, 0x1a, 0x30, 0x87, 0xc2, 0x33, 0x38, 0xcd,
	0x12, 0xde, 0xba, 0xc9, 0x50, 0x85, 0x08, 0x7d, 0x3b, 0x5e, 0x15, 0x69, 0xb5, 0x10, 0xfb, 0x66,
	0x4d, 0xff, 0x56, 0xa1, 0x4c, 0x8b, 0xc0, 0x9b, 0x90, 0xe8, 0x84, 0x39, 0x44, 0x29, 0x74, 0xf4,
	0x7d, 0x8d, 0x81, 0x6f, 0x6f, 0xdb, 0xda, 0xf4, 0x56, 0xd5, 0x42, 0x04, 0x1d, 0x7b, 0xd3, 0xd6,
	0x46, 0xc6, 0x6a, 0x3f, 0xb0, 0xcc, 0xc6, 0xca, 0xbc, 0x5d, 0xa9, 0x3a, 0xd7, 0xf3, 0x25, 0x7d,
	0x0a, 0xb0, 0x90, 0x62, 0xfd, 0xa1, 0x2d, 0xd5, 0xea, 0xd0, 0x31, 0xf4, 0xb4, 0x70, 0xa7, 0x9e,
	0x3d, 0x6d, 0xf0, 0x3f, 0x4b, 0x5e, 0xc1, 0xe3, 0x2c, 0xe1, 0xaf, 0xa5, 0xc8, 0x8b, 0x79, 0xae,
	0x34, 0x0d, 0xe0, 0x78, 0xbb, 0x8c, 0x0a, 0xc8, 0xc4, 0x8f, 0x06, 0x6c, 0x07, 0x1b, 0x46, 0xef,
	0x2f, 0x8c, 0x7e, 0x8b, 0xf1, 0xbb, 0x07, 0xa7, 0x3c, 0xc9, 0x98, 0x28, 0xd1, 0x84, 0xf5, 0x66,
	0x99, 0x57, 0x37, 0x78, 0x70, 0x64, 0xe7, 0xd0, 0x95, 0x86, 0xa1, 0xb0, 0xdc, 0x1d, 0xe6, 0x10,
	0x7d, 0xd9, 0xda, 0xa1, 0x9f, 0x3c, 0x8b, 0x77, 0x1f, 0x52, 0xfc, 0x87, 0x64, 0xbc, 0x83, 0x5b,
	0x5f, 0xe3, 0xaf, 0x04, 0x7a, 0xbb, 0x56, 0x8b, 0x9e, 0xfc, 0x46, 0x3f, 0x86, 0x9e, 0xa9, 0x2e,
	0xf2, 0x35, 0x3a, 0x43, 0x0d, 0xa6, 0x4f, 0xe0, 0xa8, 0xc4, 0x3b, 0x2c, 0x5d, 0xa6, 0x5b, 0x60,
	0x98, 0xd4, 0x7c, 0x29, 0x44, 0x69, 0x2d, 0x0d, 0x98, 0x43, 0x74, 0x04, 0xbe, 0xc2, 0xcf, 0xc1,
	0x91, 0x6d, 0x9a, 0xd2, 0x70, 0x97, 0xb9, 0xd2, 0x7a, 0xb5, 0xc6, 0xa0, 0x6b, 0x55, 0x1b, 0x1c,
	0xfe, 0x20, 0x40, 0x5b, 0x1b, 0x30, 0xdc, 0xdc, 0xa2, 0xd2, 0xff, 0x2d, 0xb5, 0x17, 0xe0, 0x4b,
	0xdc, 0x58, 0x87, 0xc3, 0x3d, 0xa1, 0x39, 0xc9, 0x98, 0xe1, 0x66, 0x76, 0x5f, 0x23, 0x33, 0x03,
	0x61, 0x04, 0xc7, 0x0e, 0xd3, 0x01, 0x9c, 0xb0, 0xcb, 0xe9, 0xbb, 0xeb, 0x69, 0xca, 0x67, 0xa3,
	0x47, 0x74, 0x08, 0x30, 0x7d, 0xc5, 0x67, 0xd7, 0xd3, 0xcb, 0xf7, 0xe9, 0xc5, 0x88, 0x84, 0xdf,
	0x08, 0x9c, 0x65, 0x09, 0xff, 0xc5, 0xa6, 0x6a, 0x51, 0x29, 0xdc, 0x1b, 0xb4, 0x73, 0xe4, 0x1d,
	0xe8, 0xa8, 0x79, 0x7f, 0x7f, 0xe2, 0x1f, 0xf6, 0xfe, 0x1f, 0xbb, 0xf6, 0xd7, 0xf3, 0xfc, 0x67,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xbe, 0x80, 0x9e, 0x89, 0x04, 0x00, 0x00,
}
