// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package dbProto is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
	Property
*/
package dbProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	RoleIdList      []uint64 `protobuf:"varint,1,rep,packed,name=roleIdList" json:"roleIdList,omitempty"`
	LastLoginRoleId uint64   `protobuf:"varint,2,opt,name=lastLoginRoleId" json:"lastLoginRoleId,omitempty"`
	CreateTime      uint64   `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	Flag            uint64   `protobuf:"varint,4,opt,name=flag" json:"flag,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetRoleIdList() []uint64 {
	if m != nil {
		return m.RoleIdList
	}
	return nil
}

func (m *User) GetLastLoginRoleId() uint64 {
	if m != nil {
		return m.LastLoginRoleId
	}
	return 0
}

func (m *User) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetFlag() uint64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type Property struct {
	UserId     string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	RoleName   string `protobuf:"bytes,2,opt,name=roleName" json:"roleName,omitempty"`
	CreateTime uint64 `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	School     uint32 `protobuf:"varint,4,opt,name=school" json:"school,omitempty"`
	Sex        uint32 `protobuf:"varint,5,opt,name=sex" json:"sex,omitempty"`
	Level      uint32 `protobuf:"varint,6,opt,name=level" json:"level,omitempty"`
	Exp        uint32 `protobuf:"varint,7,opt,name=exp" json:"exp,omitempty"`
	AllExp     uint32 `protobuf:"varint,8,opt,name=allExp" json:"allExp,omitempty"`
	Money      uint32 `protobuf:"varint,9,opt,name=money" json:"money,omitempty"`
	Yuanbao    uint32 `protobuf:"varint,10,opt,name=yuanbao" json:"yuanbao,omitempty"`
}

func (m *Property) Reset()                    { *m = Property{} }
func (m *Property) String() string            { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()               {}
func (*Property) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Property) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Property) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Property) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Property) GetSchool() uint32 {
	if m != nil {
		return m.School
	}
	return 0
}

func (m *Property) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Property) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Property) GetExp() uint32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Property) GetAllExp() uint32 {
	if m != nil {
		return m.AllExp
	}
	return 0
}

func (m *Property) GetMoney() uint32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *Property) GetYuanbao() uint32 {
	if m != nil {
		return m.Yuanbao
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "dbProto.User")
	proto.RegisterType((*Property)(nil), "dbProto.Property")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xf4, 0x30,
	0x10, 0x87, 0xc9, 0xdb, 0x6e, 0xff, 0x0c, 0xbc, 0x28, 0x41, 0x96, 0xc1, 0x83, 0x94, 0x3d, 0xf5,
	0xe4, 0xc5, 0xcf, 0xe0, 0x61, 0x61, 0x91, 0x25, 0xe8, 0x07, 0x48, 0xb7, 0xe3, 0x5a, 0x48, 0x9b,
	0x92, 0x74, 0xa5, 0xbd, 0xfb, 0xa1, 0x3d, 0x4a, 0x26, 0xab, 0x2c, 0x5e, 0xbc, 0xcd, 0xf3, 0x64,
	0x66, 0x7e, 0x03, 0x01, 0x38, 0x79, 0x72, 0xf7, 0xa3, 0xb3, 0x93, 0x95, 0x79, 0xdb, 0xec, 0x43,
	0xb1, 0xf9, 0x10, 0x90, 0xbe, 0x78, 0x72, 0xf2, 0x0e, 0xc0, 0x59, 0x43, 0xdb, 0x76, 0xd7, 0xf9,
	0x09, 0x45, 0x95, 0xd4, 0xa9, 0xba, 0x30, 0xb2, 0x86, 0x2b, 0xa3, 0xfd, 0xb4, 0xb3, 0xc7, 0x6e,
	0x50, 0xac, 0xf1, 0x5f, 0x25, 0xea, 0x54, 0xfd, 0xd6, 0x61, 0xd3, 0xc1, 0x91, 0x9e, 0xe8, 0xb9,
	0xeb, 0x09, 0x13, 0x6e, 0xba, 0x30, 0x52, 0x42, 0xfa, 0x6a, 0xf4, 0x11, 0x53, 0x7e, 0xe1, 0x7a,
	0xf3, 0x29, 0xa0, 0xd8, 0x3b, 0x3b, 0x92, 0x9b, 0x16, 0xb9, 0x86, 0x2c, 0x9c, 0xba, 0x6d, 0x51,
	0x54, 0xa2, 0x2e, 0xd5, 0x99, 0xe4, 0x2d, 0x14, 0xe1, 0xa0, 0x27, 0xdd, 0x13, 0x67, 0x97, 0xea,
	0x87, 0xff, 0x0c, 0x5d, 0x43, 0xe6, 0x0f, 0x6f, 0xd6, 0x1a, 0x8e, 0xfd, 0xaf, 0xce, 0x24, 0xaf,
	0x21, 0xf1, 0x34, 0xe3, 0x8a, 0x65, 0x28, 0xe5, 0x0d, 0xac, 0x0c, 0xbd, 0x93, 0xc1, 0x8c, 0x5d,
	0x84, 0xd0, 0x47, 0xf3, 0x88, 0x79, 0xec, 0xa3, 0x79, 0x0c, 0x1b, 0xb5, 0x31, 0x8f, 0xf3, 0x88,
	0x45, 0xdc, 0x18, 0x29, 0xcc, 0xf7, 0x76, 0xa0, 0x05, 0xcb, 0x38, 0xcf, 0x20, 0x11, 0xf2, 0xe5,
	0xa4, 0x87, 0x46, 0x5b, 0x04, 0xf6, 0xdf, 0xd8, 0x64, 0xfc, 0x23, 0x0f, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc7, 0x22, 0x73, 0x29, 0x9f, 0x01, 0x00, 0x00,
}
