{
	"MsgInfos" : [
		{
			"MsgType" : 1001,
			"MsgName" : "CUserLogin"
		},
		{
			"MsgType" : 1002,
			"MsgName" : "SUserLogin"
		},
		{
			"MsgType" : 1003,
			"MsgName" : "CRoleList"
		},
		{
			"MsgType" : 1004,
			"MsgName" : "SRoleList"
		},
		{
			"MsgType" : 1005,
			"MsgName" : "CCreateRole"
		},
		{
			"MsgType" : 1006,
			"MsgName" : "SCreateRole"
		},
		{
			"MsgType" : 1007,
			"MsgName" : "CEnterWorld"
		},
		{
			"MsgType" : 1008,
			"MsgName" : "SEnterWorld"
		},
		{
			"MsgType" : 1009,
			"MsgName" : "CAddMoney"
		},
		{
			"MsgType" : 1010,
			"MsgName" : "SMoneyInfo"
		},
		{
			"MsgType" : 1011,
			"MsgName" : "CAddLevel"
		},
		{
			"MsgType" : 1012,
			"MsgName" : "SLevelInfo"
		},
		{
			"MsgType" : 1013,
			"MsgName" : "CReqServerRoleInfos"
		},
		{
			"MsgType" : 1014,
			"MsgName" : "SServerRoleInfos"
		}
	]
}
