// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package dbProto is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	Name
*/
package dbProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Name struct {
	RoleName   string `protobuf:"bytes,1,opt,name=roleName" json:"roleName,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	RoleId     uint64 `protobuf:"varint,3,opt,name=roleId" json:"roleId,omitempty"`
	CreateTime uint64 `protobuf:"varint,4,opt,name=createTime" json:"createTime,omitempty"`
}

func (m *Name) Reset()                    { *m = Name{} }
func (m *Name) String() string            { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()               {}
func (*Name) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Name) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Name) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Name) GetRoleId() uint64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *Name) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Name)(nil), "dbProto.Name")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x49, 0x0a, 0x00, 0x31, 0x94, 0x8a, 0xb8,
	0x58, 0xfc, 0x12, 0x73, 0x53, 0x85, 0xa4, 0xb8, 0x38, 0x8a, 0xf2, 0x73, 0x52, 0x41, 0x6c, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x8c, 0x8b, 0x0d, 0xa4, 0xd5, 0x33, 0x45,
	0x82, 0x09, 0x2c, 0x03, 0xe5, 0x81, 0xc4, 0x41, 0x6a, 0x3c, 0x53, 0x24, 0x98, 0x15, 0x18, 0x35,
	0x58, 0x82, 0xa0, 0x3c, 0x21, 0x39, 0x2e, 0xae, 0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x90, 0xcc,
	0xdc, 0x54, 0x09, 0x16, 0xb0, 0x1c, 0x92, 0x48, 0x12, 0x1b, 0xd8, 0x0d, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x12, 0xe5, 0x17, 0xfa, 0x91, 0x00, 0x00, 0x00,
}
