// Code generated by protoc-gen-go.
// source: global.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	global.proto

It has these top-level messages:
	SGServerStart
	SGUserAuth
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// msgtype = 1
type SGServerStart struct {
	ZoneId uint32 `protobuf:"varint,1,opt,name=zoneId" json:"zoneId,omitempty"`
	Plat   uint32 `protobuf:"varint,2,opt,name=plat" json:"plat,omitempty"`
}

func (m *SGServerStart) Reset()                    { *m = SGServerStart{} }
func (m *SGServerStart) String() string            { return proto.CompactTextString(m) }
func (*SGServerStart) ProtoMessage()               {}
func (*SGServerStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SGServerStart) GetZoneId() uint32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *SGServerStart) GetPlat() uint32 {
	if m != nil {
		return m.Plat
	}
	return 0
}

// msgtype = 2
type SGUserAuth struct {
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *SGUserAuth) Reset()                    { *m = SGUserAuth{} }
func (m *SGUserAuth) String() string            { return proto.CompactTextString(m) }
func (*SGUserAuth) ProtoMessage()               {}
func (*SGUserAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SGUserAuth) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SGUserAuth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*SGServerStart)(nil), "protocol.SGServerStart")
	proto.RegisterType((*SGUserAuth)(nil), "protocol.SGUserAuth")
}

func init() { proto.RegisterFile("global.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0xc9, 0x4f,
	0x4a, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a,
	0xd6, 0x5c, 0xbc, 0xc1, 0xee, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0xc1, 0x25, 0x89, 0x45, 0x25,
	0x42, 0x62, 0x5c, 0x6c, 0x55, 0xf9, 0x79, 0xa9, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc,
	0x41, 0x50, 0x9e, 0x90, 0x10, 0x17, 0x4b, 0x41, 0x4e, 0x62, 0x89, 0x04, 0x13, 0x58, 0x14, 0xcc,
	0x56, 0xb2, 0xe2, 0xe2, 0x0a, 0x76, 0x0f, 0x2d, 0x4e, 0x2d, 0x72, 0x2c, 0x2d, 0xc9, 0x00, 0xe9,
	0x2c, 0x2d, 0x4e, 0x2d, 0x82, 0xea, 0xe4, 0x0c, 0x82, 0xf2, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0xf2,
	0xb3, 0x53, 0xf3, 0xc0, 0x5a, 0x39, 0x83, 0x20, 0x9c, 0x24, 0x36, 0xb0, 0x13, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x42, 0x37, 0xeb, 0x53, 0x99, 0x00, 0x00, 0x00,
}
